### ISSUE TITLE
Error when used on Windows

### ISSUE THREAD

**Issue by arrancorbett** [eoyilmaz/timecode#11]
Hi

Receiving the following error on windows when trying to use this (works fine on mac)

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\timecode\__init__.py", line 64, in __init__
    self.framerate = framerate
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\timecode\__init__.py", line 97, in framerate
    if isinstance(framerate, basestring) and '/' in framerate:
NameError: name 'basestring' is not defined

Very simple example script that is being used in this instance

```
from timecode import Timecode

inPoint = Timecode('25', '00:00:10:00')
startTimecode = Timecode('25', '01:00:00:00')
print(startTimecode - inPoint)

**Comment by eoyilmaz** [comment]
Fixed in bd3488a
