### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by kenokenobingo** [eoyilmaz/timecode#20]
Test are failing for compairing two timecodes.

```
$ python test_timecode.py

F.........E..E..............
======================================================================
ERROR: test_gt_overload (__main__.TimecodeTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_timecode.py", line 1034, in test_gt_overload
    self.assertFalse(tc1 < tc2)
TypeError: '<' not supported between instances of 'Timecode' and 'Timecode'

======================================================================
ERROR: test_le_overload (__main__.TimecodeTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_timecode.py", line 1025, in test_le_overload
    self.assertTrue(tc5 > tc4)
TypeError: '>' not supported between instances of 'Timecode' and 'Timecode'

======================================================================
FAIL: test_2398_vs_23976 (__main__.TimecodeTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_timecode.py", line 103, in test_2398_vs_23976
    self.assertEqual(timeobj1.frames, timeobj2.frames)
AssertionError: 348144 != 333639

----------------------------------------------------------------------
Ran 28 tests in 0.007s

FAILED (failures=1, errors=2)
```

**Comment by eoyilmaz** [comment]
It ıs workıng for me. What Python version are you testing with?
