### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by rgodement** [eoyilmaz/timecode#43]
Hi,

When trying to execute the following line of code:

`subtitle["start"] = Timecode(self.framerate, str(datetime.timedelta(seconds=float(r["start_time"]))))`

I got the following error:

```
Traceback (most recent call last):
  File "json_to_srt.py", line 333, in <module>
    JsonToSrt.create_subtitles()
  File "json_to_srt.py", line 106, in create_subtitles
    subtitle["start"] = Timecode(self.framerate, str(datetime.timedelta(seconds=float(r["start_time"]))))
  File "C:\Users\r.godement\AppData\Local\Programs\Python\Python38\lib\site-packages\timecode\__init__.py", line 77, in __init__
    self.frames = self.tc_to_frames(start_timecode)
  File "C:\Users\r.godement\AppData\Local\Programs\Python\Python38\lib\site-packages\timecode\__init__.py", line 209, in tc_to_frames
    hours, minutes, seconds, frames = map(int, self.parse_timecode(timecode))
  File "C:\Users\r.godement\AppData\Local\Programs\Python\Python38\lib\site-packages\timecode\__init__.py", line 337, in parse_timecode
    frs = int(bfr[3])
IndexError: list index out of range
```

**Comment by rgodement** [comment]
I found the problem, which was due to the _datetime_ library not indicating milliseconds when input a round float like 15.0.
For instance:
```print(str(datetime.timedelta(seconds=15.0)))
'0:00:15'
```
But the Timecode function needs the milliseconds to be indicated.

**Comment by eoyilmaz** [comment]
👍
